name: Remote Dispatch Action Responder
 
on: [repository_dispatch, push]
jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
      - name: PONG - Dispatch response to received PING
        if: github.event.action == 'ping'
        run: |
          curl -X POST https://api.github.com/repos/jasminhusadzic/platerate-staging-test/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "pong", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'      
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: nanasess/setup-chromedriver@master
      with:
       chromedriver-version: '77.0.3865.40'
    - run: |
       export DISPLAY=:99
       chromedriver --url-base=/wd/hub &
       sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
    
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        ./node_modules/.bin/wdio wdio.conf.js
    - name: Upload math result for job 1
      uses: actions/upload-artifact@v1
      with:
          name: report
          path: ./output/report.html
     
  email:
   runs-on: ubuntu-latest
   steps:
    - name: Download math result for job 2
      uses: actions/download-artifact@v1
      with:
          name: report
    - name: Send mail
      uses: dawidd6/action-send-mail@v2
      with:
       server_address: smtp.gmail.com
       server_port: 465
       username: ${{secrets.MAIL_USERNAME}}
       password: ${{secrets.MAIL_PASSWORD}}
       subject: Github Actions job result
       # Literal body:
       body: Build job of ${{github.repository}} completed successfully!
       to: jasmin.husadzic@gmail.com
       from: Luke Skywalker # <user@example.com>
       # Optional content type (defaults to text/plain):
       content_type: text/html
       # Optional attachments:
       attachments: report/report.html

      env:
        CI: true
