name: Manual Run
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: nanasess/setup-chromedriver@master
      with:
       chromedriver-version: '77.0.3865.40'
    - run: |
       export DISPLAY=:99
       chromedriver --url-base=/wd/hub &
       sudo Xvfb -ac :99 -screen 0 1920x1280x24 > /dev/null 2>&1 & # optional
    
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm install
    - name: Run tests on test environment
      if: always()
      run: ENV=test npm run test
    - name: Upload report
      if: always()
      uses: actions/upload-artifact@v2-preview
      with:
          name: report
          path: ./output/*.html
  email:
   if: always()
   needs: [build] 
   runs-on: ubuntu-latest
   steps:
    - name: Download report
      uses: actions/download-artifact@v2-preview
      with:
          name: report
          path: ./ready
    - name: Send mail
      uses: dawidd6/action-send-mail@v2
      with:
       server_address: smtp.gmail.com
       server_port: 465
       username: platerateqa
       password: jasmin2906
       subject: Test Automation Report Search suite
       # Literal body:
       body: Test automation report in attachments!
       to: jasmin.husadzic@gmail.com
       from: PlateRate QA Automation Department # <user@example.com>
       # Optional content type (defaults to text/plain):
       content_type: text/html
       # Optional attachments:
       attachments: ./ready/test_report.html, ./ready/staging_report.html, ./ready/prod_report.html
